config/routes.rb
Rails.application.routes.draw do
  resources :socials
  resources :technical_englishes
  resources :economics
  resources :anwendungs_systems
  resources :it_systems
  resources :moods
  resources :aspirations

  root 'aspirations#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/mood.rb
class Mood < ActiveRecord::Base
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:mood_count, :activity, :time)
    end
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/moods/_form.html.haml
= form_for @mood do |f|
  - if @mood.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mood.errors.count, "error")} prohibited this mood from being saved:"
      %ul
        - @mood.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :mood_count
    = f.select :mood_count, [1,2,3,4,5,6,7,8,9,10]
  .field
    = f.label :activity
    = f.text_field :activity
  .field
    = f.label :time
    = f.datetime_select :time
  .actions
    = f.submit 'Save'

app/views/moods/edit.html.haml
%h1 Editing mood

= render 'form'

= link_to 'Show', @mood
\|
= link_to 'Back', moods_path

app/views/moods/index.html.haml
%h1 Listing moods

%table
  %thead
    %tr
      %th Mood count
      %th Activity
      %th Time
      %th Options

  %tbody
    - @moods.each do |mood|
      %tr
        %td= mood.mood_count #{/10}
        %td= mood.activity
        %td= mood.time.strftime("%H:%M - %d.%m.%y")
        %td
          %ul
            %li
              = link_to 'Show', mood
            %li
              = link_to 'Edit', edit_mood_path(mood)
            %li
              = link_to 'Destroy', mood, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Mood', new_mood_path

app/views/moods/new.html.haml
%h1 New mood

= render 'form'

= link_to 'Back', moods_path

app/views/moods/show.html.haml
%p#notice= notice

%p
  %b Mood count:
  = @mood.mood_count
%p
  %b Activity:
  = @mood.activity
%p
  %b Time:
  = @mood.time

= link_to 'Edit', edit_mood_path(@mood)
\|
= link_to 'Back', moods_path