config/routes.rb
Rails.application.routes.draw do
  resources :socials
  resources :technical_englishes
  resources :economics
  resources :anwendungs_systems
  resources :it_systems
  resources :moods
  resources :aspirations

  root 'aspirations#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/economic.rb
class Economic < ActiveRecord::Base
end

app/controllers/economics_controller.rb
class EconomicsController < ApplicationController
  before_action :set_economic, only: [:show, :edit, :update, :destroy]

  # GET /economics
  # GET /economics.json
  def index
    @economics = Economic.all
  end

  # GET /economics/1
  # GET /economics/1.json
  def show
  end

  # GET /economics/new
  def new
    @economic = Economic.new
  end

  # GET /economics/1/edit
  def edit
  end

  # POST /economics
  # POST /economics.json
  def create
    @economic = Economic.new(economic_params)

    respond_to do |format|
      if @economic.save
        format.html { redirect_to @economic, notice: 'Economic was successfully created.' }
        format.json { render :show, status: :created, location: @economic }
      else
        format.html { render :new }
        format.json { render json: @economic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /economics/1
  # PATCH/PUT /economics/1.json
  def update
    respond_to do |format|
      if @economic.update(economic_params)
        format.html { redirect_to @economic, notice: 'Economic was successfully updated.' }
        format.json { render :show, status: :ok, location: @economic }
      else
        format.html { render :edit }
        format.json { render json: @economic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /economics/1
  # DELETE /economics/1.json
  def destroy
    @economic.destroy
    respond_to do |format|
      format.html { redirect_to economics_url, notice: 'Economic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_economic
      @economic = Economic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def economic_params
      params.require(:economic).permit(:topic, :learning, :understood, :subject, :repeat)
    end
end

app/helpers/economics_helper.rb
module EconomicsHelper
end

app/views/economics/_form.html.haml
= simple_form_for(@economic) do |f|
  = f.error_notification

  .form-inputs
    = f.input :topic
    = f.input :learning
    = f.input :understood
    = f.input :subject
    = f.input :repeat

  .form-actions
    = f.button :submit

app/views/economics/edit.html.haml
%h1 Editing economic

= render 'form'

= link_to 'Show', @economic
\|
= link_to 'Back', economics_path

app/views/economics/index.html.haml
%h1 Listing economics

%table
  %thead
    %tr
      %th Topic
      %th Learning
      %th Understood
      %th Subject
      %th Repeat
      %th
      %th
      %th

  %tbody
    - @economics.each do |economic|
      %tr
        %td= economic.topic
        %td= economic.learning
        %td= economic.understood
        %td= economic.subject
        %td= economic.repeat
        %td= link_to 'Show', economic
        %td= link_to 'Edit', edit_economic_path(economic)
        %td= link_to 'Destroy', economic, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Economic', new_economic_path

app/views/economics/new.html.haml
%h1 New economic

= render 'form'

= link_to 'Back', economics_path

app/views/economics/show.html.haml
%p#notice= notice

%p
  %b Topic:
  = @economic.topic
%p
  %b Learning:
  = @economic.learning
%p
  %b Understood:
  = @economic.understood
%p
  %b Subject:
  = @economic.subject
%p
  %b Repeat:
  = @economic.repeat

= link_to 'Edit', edit_economic_path(@economic)
\|
= link_to 'Back', economics_path