config/routes.rb
Rails.application.routes.draw do
  resources :socials
  resources :technical_englishes
  resources :economics
  resources :anwendungs_systems
  resources :it_systems
  resources :moods
  resources :aspirations

  root 'aspirations#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/aspiration.rb
class Aspiration < ActiveRecord::Base
  NUMBERS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
end

app/controllers/aspirations_controller.rb
class AspirationsController < ApplicationController
  before_action :set_aspiration, only: [:show, :edit, :update, :destroy]

  # GET /aspirations
  # GET /aspirations.json
  def index
    @aspirations = Aspiration.all
  end

  # GET /aspirations/1
  # GET /aspirations/1.json
  def show
  end

  # GET /aspirations/new
  def new
    @aspiration = Aspiration.new
  end

  # GET /aspirations/1/edit
  def edit
  end

  # POST /aspirations
  # POST /aspirations.json
  def create
    @aspiration = Aspiration.new(aspiration_params)

    respond_to do |format|
      if @aspiration.save
        format.html { redirect_to @aspiration, notice: 'Aspiration was successfully created.' }
        format.json { render :show, status: :created, location: @aspiration }
      else
        format.html { render :new }
        format.json { render json: @aspiration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aspirations/1
  # PATCH/PUT /aspirations/1.json
  def update
    respond_to do |format|
      if @aspiration.update(aspiration_params)
        format.html { redirect_to @aspiration, notice: 'Aspiration was successfully updated.' }
        format.json { render :show, status: :ok, location: @aspiration }
      else
        format.html { render :edit }
        format.json { render json: @aspiration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aspirations/1
  # DELETE /aspirations/1.json
  def destroy
    @aspiration.destroy
    respond_to do |format|
      format.html { redirect_to aspirations_url, notice: 'Aspiration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aspiration
      @aspiration = Aspiration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aspiration_params
      params.require(:aspiration).permit(:aspiration, :start, :end, :unit, :amount, :category, :description, :coin)
    end
end

app/helpers/aspirations_helper.rb
module AspirationsHelper
end

app/views/aspirations/_form.html.haml
= form_for @aspiration do |f|
  - if @aspiration.errors.any?
    #error_explanation
      %h2= "#{pluralize(@aspiration.errors.count, "error")} prohibited this aspiration from being saved:"
      %ul
        - @aspiration.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :aspiration
    = f.text_field :aspiration
  .field
    = f.label :start
    = f.datetime_select :start
  .field
    = f.label :end
    = f.datetime_select :end
  .field
    = f.label :unit
    = f.text_field :unit
  .field
    = f.label :amount
    = f.number_field :amount
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :coin
    = f.number_field :coin
  .actions
    = f.submit 'Save'

app/views/aspirations/edit.html.haml
%h1 Editing aspiration

= render 'form'

= link_to 'Show', @aspiration
\|
= link_to 'Back', aspirations_path

app/views/aspirations/index.html.haml
%h1 All my Aspirations.
%p.lead Whatever you ever dreamed of. It can become true. Just do it. Damn thats nike's slogan. But still true.
%p.lead
  %a.btn.btn-lg.btn-default{:href => "#"} Learn more
  %h1 Listing aspirations

%table
  %thead
    %tr
      %th Aspiration
      %th Start
      %th End
      %th Unit
      %th Amount
      %th Category
      %th Description
      %th Coin
      %th Options


  %tbody
    - @aspirations.each do |aspiration|
      %tr
        %td= aspiration.aspiration
        %td= aspiration.start.strftime("%d.%m.%y")
        %td= aspiration.end.strftime("%d.%m.%y")
        %td= aspiration.unit
        %td= aspiration.amount
        %td= aspiration.category
        %td= aspiration.description
        %td= aspiration.coin
        %td
          %ul
            %li
              = link_to 'Show', aspiration
            %li
              = link_to 'Edit', edit_aspiration_path(aspiration)
            %li
              = link_to 'Destroy', aspiration, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Aspiration', new_aspiration_path

app/views/aspirations/new.html.haml
%h1 New aspiration

= render 'form'

= link_to 'Back', aspirations_path

app/views/aspirations/show.html.haml
%p#notice= notice

%p
  %b Aspiration:
  = @aspiration.aspiration
%p
  %b Start:
  = @aspiration.start
%p
  %b End:
  = @aspiration.end
%p
  %b Unit:
  = @aspiration.unit
%p
  %b Amount:
  = @aspiration.amount
%p
  %b Category:
  = @aspiration.category
%p
  %b Description:
  = @aspiration.description
%p
  %b Coin:
  = @aspiration.coin

= link_to 'Edit', edit_aspiration_path(@aspiration)
\|
= link_to 'Back', aspirations_path