config/routes.rb
Rails.application.routes.draw do
  resources :socials
  resources :technical_englishes
  resources :economics
  resources :anwendungs_systems
  resources :it_systems
  resources :moods
  resources :aspirations

  root 'aspirations#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/technical_english.rb
class TechnicalEnglish < ActiveRecord::Base
end

app/controllers/technical_englishes_controller.rb
class TechnicalEnglishesController < ApplicationController
  before_action :set_technical_english, only: [:show, :edit, :update, :destroy]

  # GET /technical_englishes
  # GET /technical_englishes.json
  def index
    @technical_englishes = TechnicalEnglish.all
  end

  # GET /technical_englishes/1
  # GET /technical_englishes/1.json
  def show
  end

  # GET /technical_englishes/new
  def new
    @technical_english = TechnicalEnglish.new
  end

  # GET /technical_englishes/1/edit
  def edit
  end

  # POST /technical_englishes
  # POST /technical_englishes.json
  def create
    @technical_english = TechnicalEnglish.new(technical_english_params)

    respond_to do |format|
      if @technical_english.save
        format.html { redirect_to @technical_english, notice: 'Technical english was successfully created.' }
        format.json { render :show, status: :created, location: @technical_english }
      else
        format.html { render :new }
        format.json { render json: @technical_english.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technical_englishes/1
  # PATCH/PUT /technical_englishes/1.json
  def update
    respond_to do |format|
      if @technical_english.update(technical_english_params)
        format.html { redirect_to @technical_english, notice: 'Technical english was successfully updated.' }
        format.json { render :show, status: :ok, location: @technical_english }
      else
        format.html { render :edit }
        format.json { render json: @technical_english.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technical_englishes/1
  # DELETE /technical_englishes/1.json
  def destroy
    @technical_english.destroy
    respond_to do |format|
      format.html { redirect_to technical_englishes_url, notice: 'Technical english was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technical_english
      @technical_english = TechnicalEnglish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technical_english_params
      params.require(:technical_english).permit(:topic, :learning, :understood, :subject, :repeat)
    end
end

app/helpers/technical_englishes_helper.rb
module TechnicalEnglishesHelper
end

app/views/technical_englishes/_form.html.haml
= simple_form_for(@technical_english) do |f|
  = f.error_notification

  .form-inputs
    = f.input :topic
    = f.input :learning
    = f.input :understood
    = f.input :subject
    = f.input :repeat

  .form-actions
    = f.button :submit

app/views/technical_englishes/edit.html.haml
%h1 Editing technical_english

= render 'form'

= link_to 'Show', @technical_english
\|
= link_to 'Back', technical_englishes_path

app/views/technical_englishes/index.html.haml
%h1 Listing technical_englishes

%table
  %thead
    %tr
      %th Topic
      %th Learning
      %th Understood
      %th Subject
      %th Repeat
      %th
      %th
      %th

  %tbody
    - @technical_englishes.each do |technical_english|
      %tr
        %td= technical_english.topic
        %td= technical_english.learning
        %td= technical_english.understood
        %td= technical_english.subject
        %td= technical_english.repeat
        %td= link_to 'Show', technical_english
        %td= link_to 'Edit', edit_technical_english_path(technical_english)
        %td= link_to 'Destroy', technical_english, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Technical english', new_technical_english_path

app/views/technical_englishes/new.html.haml
%h1 New technical_english

= render 'form'

= link_to 'Back', technical_englishes_path

app/views/technical_englishes/show.html.haml
%p#notice= notice

%p
  %b Topic:
  = @technical_english.topic
%p
  %b Learning:
  = @technical_english.learning
%p
  %b Understood:
  = @technical_english.understood
%p
  %b Subject:
  = @technical_english.subject
%p
  %b Repeat:
  = @technical_english.repeat

= link_to 'Edit', edit_technical_english_path(@technical_english)
\|
= link_to 'Back', technical_englishes_path